controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
auth:
  path: /api/auth
  methods: ["POST"]

api_order_pay:
    path: /api/orders/{id}/pay
    controller: App\Controller\OrderController::payOrder

api_order_add_drinks:
    path: /api/orders/{id}/addDrink
    controller: App\Controller\OrderAddDrinksController::addDrinksToOrder

api_order_remove_drink:
    path: /api/orders/{orderId}/removeDrink/{drinkId}
    controller: App\Controller\OrderController::removeDrinkFromOrder
